#!/bin/bash

DOCKER_IP=${DOCKER_IP:-127.0.0.1}

waitport() {
  local TIMES=0
  echo waiting $1:$2
  while ! nc -z "$1" "$2" 2> /dev/null ; do
    sleep 0.2
    TIMES=$((TIMES+1))
    if [ "$TIMES" -gt "$3" ] ; then
      echo failed wait
      return 1
    fi
  done
  return 0
}

sqlite3() {
  go test -v
  return $?
}

postgres() {
  ID=$(docker run -p 5432 -d postgres:9.4)
  PORT=$(docker port "$ID" 5432 | cut -d : -f 2)
  waitport "$DOCKER_IP" "$PORT" 50 || return 1
  DATABASE_URI="postgres://user=postgres password=postgres dbname=postgres host=$DOCKER_IP port=$PORT sslmode=disable" go test -v
  S=$?
  docker rm -f $ID
  return $S
}

mysql() {
  ID=$(docker run \
    -e MYSQL_ROOT_PASSWORD=root \
    -e MYSQL_USER=mysql \
    -e MYSQL_PASSWORD=mysql \
    -e MYSQL_DATABASE=mysql \
    -p 3306 -d mysql:5.7)
  PORT=$(docker port "$ID" 3306 | cut -d : -f 2)
  waitport $DOCKER_IP "$PORT" 50 || return 1
  DATABASE_URI="mysql://mysql:mysql@tcp($DOCKER_IP:$PORT)/mysql?charset=utf8&parseTime=True" go test -v
  S=$?
  docker rm -f $ID
  return $S
}

sqlite3 || exit 1
postgres || exit 1
mysql || exit 1
